### ISSUE TITLE
add helper function to wait for blocks

### ISSUE THREAD

**Issue by bekauz** [timewave-computer/localic-utils#7]
in our current e2e tests there are cases where multiple execute messages are submitted too close to each other which causes account sequence mismatch.

to avoid that, we can poll the chain for a block height delta and block execution until some number of blocks had passed.

lets expose a `wait_for_blocks` method on chain/rb which will take in a `u64` and sleep until that block height delta had passed.

**Comment by dev0614** [comment]
This is necessary.

How about consider adding optional timeout parameter to the `wait_for_blocks` method to prevent infinite waiting when there is network issues or unexpected delays in block production?
Exactly, timeout handling is very important to implement that feature, I think
